name: CI/CD
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Use Cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      
      - name: Install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run train.py
        run: |
          . .venv/bin/activate
          python app/train.py

      - name: Run tests
        run: |
          . .venv/bin/activate
          pytest

        env:
          CI: true
  
  deploy:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Use SSH key  
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
      

      - name: Copy files to EC2
        run: |
          scp -r -o StrictHostKeyChecking=no ./* ec2-user@${{ secrets.EC2_IP }}:/home/ec2-user/ml-inference-server

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_IP }} << 'EOF'
            cd /home/ec2-user/MLOps-EC2-practice
            source .venv/bin/activate
            pip install -r requirements.txt
            nohup uvicorn app.inference:app --host 0.0.0.0 --port 8000 &
          EOF